### ISSUE TITLE
Q/A experiments report

### ISSUE THREAD

**Issue by arezae** [MedBot-team/NaBot#10]
A comparison report on Huggingface Q/A system fine-tune with our data.

1. Baseline model is Q/A model from Huggingface - bert_base
2. (1) + fine tune language model on our data
3. (1) + finetune Q/A on our 200 Q/A
4. (2) + fine tune on our 200 Q/A 

We need to know how important is the fine-tune on our language model and fine-tune on our Q/A

**Comment by nafarieh** [comment]
The `bert-base-uncased` model which fine tuned by `deepset/bert-base-cased-squad2` model:

09/19/2021 16:28:58 - INFO - __main__ - Results: {'exact': 5.687203791469194, 'f1': 31.57154563090946, 'total': 211, 'HasAns_exact': 5.687203791469194, 'HasAns_f1': 31.57154563090946, 'HasAns_total': 211, 'best_exact': 5.687203791469194, 'best_exact_thresh': 0.0, 'best_f1': 31.57154563090946, 'best_f1_thresh': 0.0}

 The `bert-base-uncased` model which fine tuned by `MLM in our Dataset + QA Squad + QA Our Dataset`  model:

09/19/2021 17:47:46 - INFO - __main__ - Results: {'exact': 50.71090047393365, 'f1': 74.54551157490803, 'total': 211, 'HasAns_exact': 50.71090047393365, 'HasAns_f1': 74.54551157490803, 'HasAns_total': 211, 'best_exact': 50.71090047393365, 'best_exact_thresh': 0.0, 'best_f1': 74.54551157490803, 'best_f1_thresh': 0.0}

**Comment by nafarieh** [comment]
`1-` The `bert-base` model which fine tuned by `deepset/bert-base-cased-squad2` model:

`2-`  The `bert-base` model which fine tuned by `MLM in our Dataset + QA Squad`  model:

`3-`  The `deepset/bert-base-cased-squad2` model which fine tuned by `QA Squad + QA Our Dataset`  model:

`4-`  The `bert-base` model which fine tuned by `MLM in our Dataset + QA Squad + QA Our Dataset`  model:

**Comment by arezae** [comment]
Thanks for the updates. It would easier to compare if have them in a single table or graph.

**Comment by Ali-Razmdideh** [comment]
Thanks for your note.

| model | exact  | f1 | total | HasAns_exact | HasAns_f1 | HasAns_total | best_exact | best_exact_thresh | best_f1 |  best_f1_thresh |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Bert + Squad | 5.687203791469194  | 31.57154563090946  | 211  | 5.687203791469194  | 31.57154563090946 | 211  | 5.687203791469194  | 0.0  | 31.57154563090946 | 0.0 |
| FineTuned Bert + Squad | 10.42654028436019  | 38.48925966485835  | 211  | 10.42654028436019  | 38.48925966485835 | 211  | 10.42654028436019  | 0.0  | 38.48925966485835  | 0.0  |
| Bert + FineTuned QA | 47.39336492890995 | 71.79348969128544 | 211  | 47.39336492890995  | 71.79348969128544 | 211  | 47.39336492890995  | 0.0  | 71.79348969128544  | 0.0  |
| FineTuned Bert + FineTuned QA | 50.71090047393365 | 74.54551157490803 | 211  | 50.71090047393365  | 74.54551157490803 | 211  | 50.71090047393365  | 0.0  | 74.54551157490803  | 0.0  |
| SqueezeBERT + Squad | 4.739336492890995  | 31.57909317121808  | 211  | 4.739336492890995  |  31.57909317121808 | 211  | 4.739336492890995  | 0.0  | 31.57909317121808 | 0.0 |
| FineTuned SqueezeBERT + Squad |  3.7914691943127963  | 25.861355030166404  | 211  | 3.7914691943127963  | 25.861355030166404 | 211  | 3.7914691943127963  | 0.0  | 25.861355030166404  | 0.0  |
| SqueezeBERT + FineTuned Squad | 36.018957345971565 | 65.08729223891349 | 211  | 36.018957345971565 | 65.08729223891349 | 211  | 47.39336492890995  | 0.0  | 65.08729223891349  | 0.0  |
| FineTuned SqueezeBERT + FineTuned QA | 40.758293838862556, | 67.35364641337732 | 211  | 40.758293838862556  | 67.35364641337732 | 211  | 40.758293838862556  | 0.0  | 67.35364641337732  | 0.0  |
